### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by tgong1** [spiralgenetics/truvari#2]
Hi,

When I run truvari like ./truvari.py -b base_calls.vcf -c compare_calls.vcf -o output_dir/
I got the following error message. But I didn't get this for my another compare_calls.vcf.
Could you give some suggestions on how to solve this?
Thank you very much.

Traceback (most recent call last):
  File "truvari.py", line 926, in <module>
    run(sys.argv[1:])
  File "truvari.py", line 660, in run
    contig = list(vcfB.contigs.keys())[0]
IndexError: list index out of range

**Comment by ACEnglish** [comment]
I believe that problem may be arising because you don't have contigs defined in your header. Could you check to make sure you have `##contig=<ID=1,length=249250621>` in your comparison vcf?

I'll also put in a ticket to better handle this error and to make it more clear in the documentation that contig headers are expected in the base and comparison vcfs.

**Comment by tgong1** [comment]
Yes, it is the problem. Thank you very much!
