### ISSUE TITLE
Cannot fetch on call_h_s.vcf. Is it sorted/indexed?

### ISSUE THREAD

**Issue by songtaogui** [spiralgenetics/truvari#3]
Hi，
I was trying to evaluate my vcf files with cmd like:
`truvari.py -b baseline.vcf -c call_h_s.vcf -o truvari_out`
I have sorted my vcf files, but I still got ERRORs like:
`[ERROR] Cannot fetch on call_h_s.vcf. Is it sorted/indexed?`

And I used bgzipped & indexed vcf , with another error:
`
Traceback (most recent call last):
  File "/home/maize/gst/sftw/SV-Call/truvari/truvari.py", line 926, in <module>
    run(sys.argv[1:])
  File "/home/maize/gst/sftw/SV-Call/truvari/truvari.py", line 661, in run
    contig = vcfB.fetch(contig, 0, 1000)
  File "/home/maize/gst/sftw/anaconda2/lib/python2.7/site-packages/vcf/parser.py", line 599, in fetch
    self.reader = self._tabix.fetch(chrom, start, end)
  File "pysam/libctabix.pyx", line 447, in pysam.libctabix.TabixFile.fetch
ValueError: start out of range (1000)
`
So I was wondering what's the right Input format for the vcf files? Should they be gzipped or not?
Or that error were caused by someting else? Thank you!

Please find attached the test vcfs I used.

Best wishes,

Songtao Gui

[baseline.vcf.gz](https://github.com/spiralgenetics/truvari/files/2162675/baseline.vcf.gz)
[call_h_s.vcf.gz](https://github.com/spiralgenetics/truvari/files/2162676/call_h_s.vcf.gz)

**Comment by ACEnglish** [comment]
Hello,

I'm unable to recreate this error. 
However, when I re-run on your vcfs after running `tabix -p vcf <VCF>` on your two inputs, I do get an error saying: 
```  
  File "/home/english/truvari/truvari.py", line 931, in <module>
    run(sys.argv[1:])
  File "/home/english/truvari/truvari.py", line 811, in run
    seq_similarity = var_pctsim_lev(entryA, entryB)
  File "/home/english/truvari/truvari.py", line 145, in var_pctsim_lev
    if len(entryA.REF) < len(entryA.ALT[0]):
TypeError: object of type '_SV' has no len()```

This has to do how these aren't sequence resolved calls (i.e. using <DEL> instead of presenting the full sequence in ALT). To get around this error, one simply needs to run truvari with `--pctsim 0`

Without any more information, I'm not sure what can be done. Are you certain you were pointing at the correct files and the tabix indexes were up to date?

**Comment by songtaogui** [comment]
Hello,

Thank you for your kind reply.

I have re-run the inputs with cmds like:
`
tabix -p vcf baseline.vcf.gz
tabix -p vcf call_h_s.vcf.gz
truvari.py -b baseline.vcf.gz -c call_h_s.vcf.gz -o out [--pctsim 0]
`
with or without the `--pctsim 0` option, I got the same error saying:
`
File "/home/gst/sftw/SV-Call/truvari/truvari.py", line 926, in <module>
    run(sys.argv[1:])
  File "/home/gst/sftw/SV-Call/truvari/truvari.py", line 661, in run
    contig = vcfB.fetch(contig, 0, 1000)
  File "/home/gst/sftw/anaconda2/lib/python2.7/site-packages/vcf/parser.py", line 599, in fetch
    self.reader = self._tabix.fetch(chrom, start, end)
  File "pysam/libctabix.pyx", line 447, in pysam.libctabix.TabixFile.fetch
ValueError: start out of range (1000)
` 
It seems that something went wrong during the INPUT procedure. Any suggestions? 

Thank you!

Best wishes,

Songtao Gui

**Comment by ACEnglish** [comment]
The problem seems to be happening with pysam even though truvari is calling the function correctly.
The only instances of problems similar to this I can find are https://github.com/pysam-developers/pysam/issues/41 and https://www.biostars.org/p/113309/ but neither of these seem particularly relevant to this error.  You seem to be using python 2.7 instead of python3, and, like I said, we're not calling fetch weirdly.

Could you test the pysam directly and run something like:
```python
import vcf
v = vcf.Reader(filename="call_h_s.vcf.gz")
for x in v.fetch("7", 0, 1000): 
    print x
```

**Comment by songtaogui** [comment]
Thanks！
It was the pysam problem, Truvari works fine as soon as I used python 3 instead.
Thank you again for your help.
Best wishes.
