### ISSUE TITLE
Truvari v1.2 and v1.3.2 give different results

### ISSUE THREAD

**Issue by sjurug** [spiralgenetics/truvari#32]
Hi,

we upgraded Truvari from v1.2 to v1.3.2, and given the same input data and Truvari parameters, we get quite different results.

E.g. results for Manta DEL:
For variants larger that 1000bp, v1.2 reports approximately 450 true positives, while v1.3.2 reports 2
The two versions agree on variants smaller than 1000bp (only missing 5 of 1000 in 300to999 range)

Is this behaviour expected?

**Comment by scalavision** [comment]
I can report the same problems, here is the results using the exact same commands on the same vcf's, but with the two different versions.

Version 1.2:

https://docs.google.com/spreadsheets/d/1FvZg1fTezi0OAS4ogcH3UvGtJqWOyyTfzmsEbFuRK1Q/edit?usp=sharing

Version 1.3.2:

https://docs.google.com/spreadsheets/d/1ifmh-4sSHFy4c0xZkucBJcmC0dQFIzyb8iMAxpDQx1g/edit?usp=sharing

**Comment by ACEnglish** [comment]
Hello,

Could you please provide a set of comparison calls' VCF so that I can look for what might be happening.
Alternatively, if you could run the v1.2 and v1.3.2 commands again with `--debug` and provide the full `log.txt` files, I may be able to get an idea from those as well.

Have a great day,
~/Adam

**Comment by scalavision** [comment]
Thanks for quick response Adam, I've created a `git-lfs` repo at this location:

https://github.com/scalavision/truvari_troubleshoot

You will find both logs and vcfs there. The log for 1.3.2 is clipped at 5000 lines, because it was more then 70mb big. Please let me know if you need anything else.

**Comment by ACEnglish** [comment]
Hello,

I just put in a commit that may address this problem.
This issue was arising because pyvcf did not provide accurate `end` points for events that are not sequence-resolved (e.g. ALT:<DEL>), but pysam does provide an accurate `stop`. Version 1.2 and prior worked because the `create_haplotype` method worked around the pyvcf behavior. However, that same approach did not work after the change to pysam.

I only tested far enough to get your `manta_NACG-HG002-BenchM_diploidSV.vcf.gz` to behave the same in the fix as v1.2. Below is the summary of the three results. 
Could you please checkout 4dcac156096db30ac3f6c9c6fad6b7d1b6237993 and see if that gives results consistent with your expectations on all the other vcfs? If so, I'll push a patch bump.

Thanks,
~/Adam 

```
$ grep -w TP-base */summary.txt 
fix/summary.txt:    "TP-base": 2699,
v1.2/summary.txt:    "TP-base": 2699,
v1.3/summary.txt:    "TP-base": 2241,
$ consistency_report */tp-base.vcf
#
# Total 2699 calls across 3 VCFs
#
#File	NumCalls
fix/tp-base.vcf	2699
v1.2/tp-base.vcf	2699
v1.3/tp-base.vcf	2241
#
# Summary of consistency
#
#VCFs	Calls	Pct
3	2241	83.03%
2	458	16.97%
#
# Breakdown of VCFs' consistency
#
#Group	Total	TotalPct	PctOfFileCalls
111	2241	83.03%	83.03% 83.03% 100.00%
110	458	16.97%	16.97% 16.97% 0%
```

**Comment by scalavision** [comment]
Thanks!! I'll have a loot at it :-)

**Comment by scalavision** [comment]
@ACEnglish , I've now tested against your last release, the `1.3.4` version. As far as I can see, I now get exactly the same results between 1.2 and 1.3.4. Thank you very fixing this :-) 

Wish you a nice weekend!

**Comment by ACEnglish** [comment]
Note that I had a bad push to 1.3.3, so 1.3.4 will be your new desired version. Thanks for the help!
