### ISSUE TITLE
Truvari 1.3.4 freezes during analysis of DELLY results

### ISSUE THREAD

**Issue by ofonov** [spiralgenetics/truvari#35]
Hi,

I have attempted to use Truvari 1.3.4 for the analysis of DELLY output. Truvari freezes at the stage of creating call interval trees. Despite active --debug flag, there is no detailed information about possible problem in the log. Truvari 1.2 performs the analysis without any problems. 
DELLY sample 
[DELLY.tst.vcf.gz](https://github.com/spiralgenetics/truvari/files/3846975/DELLY.tst.vcf.gz)
Log:
2019-11-14 15:27:51,456 [INFO] Running /home/usr/miniconda3/bin/truvari --reference /home/usr/Documents/references/b37_decoy/human_g1k_v37_decoy.fasta --includebed /home/usr/Documents/GIAB/NIST_SV_Integration_v0.6/HG002_SVs_Tier1_v0.6.bed --base /home/usr/Documents/GIAB/NIST_SV_Integration_v0.6/HG002_SVs_Tier1_v0.6.vcf.gz --comp DDD/DELLY.tst.vcf.gz --output /home/usr/Documents/SV_benchmarking/truvari/DELLY.tst_TV1.3.4_2019-11-14_15-27-51 --giabreport --refdist 500 --pctsim 0 --pctsize 0.7 --pctovl 0 --sizemin 50 --sizemax 150000 --sizefilt 30 --passonly --no-ref a --prog --debug
2019-11-14 15:27:51,456 [INFO] Params:
{
    "base": "/home/usr/Documents/GIAB/NIST_SV_Integration_v0.6/HG002_SVs_Tier1_v0.6.vcf.gz",
    "comp": "DDD/DELLY.tst.vcf.gz",
    "output": "/home/usr/Documents/SV_benchmarking/truvari/DELLY.tst_TV1.3.4_2019-11-14_15-27-51",
    "reference": "/home/usr/Documents/references/b37_decoy/human_g1k_v37_decoy.fasta",
    "giabreport": true,
    "debug": true,
    "prog": true,
    "refdist": 500,
    "pctsim": 0.0,
    "pctsize": 0.7,
    "pctovl": 0.0,
    "typeignore": false,
    "gtcomp": false,
    "bSample": null,
    "cSample": null,
    "sizemin": 50,
    "sizefilt": 30,
    "sizemax": 150000,
    "passonly": true,
    "no_ref": "a",
    "includebed": "/home/usr/Documents/GIAB/NIST_SV_Integration_v0.6/HG002_SVs_Tier1_v0.6.bed",
    "multimatch": false
}
2019-11-14 15:27:52,416 [INFO] Including 34830 bed regions
2019-11-14 15:27:52,416 [INFO] Creating call interval tree for overlap search

**Comment by ACEnglish** [comment]
The program is still running. The problem is that you have enormous calls in your VCF that are being pulled by every `--includebed` region because the calls span essentially all of chromosome 1. These calls are being processed and added to the interval tree every time and therefore the program is taking a long time. This wasn't happening in v1.2 because we built the interval tree over all the calls without fetching for the `--includebed` regions. For normal datasets, this decreased the runtime and memory requirements.

I'll work on fixing truvari so that it doesn't redundantly add calls into the interval tree. In the mean time, I recommend that you pre-filter your VCF so that these giant calls are removed, or you can stick to version 1.2. 

```bash
#Retaining only calls with start/end span less than or equal to 150k
(bcftools view -h DELLY.tst.vcf.gz && bcftools query -f "%INFO/END\t%POS\t%LINE" DELLY.tst.vcf.gz | awk '{if ($1-$2 <= 150000) print $0}' | cut -f3-) | bgzip > cleaned_delly.tst.vcf.gz
```

**Comment by ofonov** [comment]
Thanks for the rapid responce!
