### ISSUE TITLE
Error parsing SVLEN=.

### ISSUE THREAD

**Issue by johnemajor** [spiralgenetics/truvari#38]
I am running truvari installed via python3 pip.  It has worked very well for a few SV files, but I hit a problem with the Mt Sinai NA12878 published SVs from GIAB(ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NA12878_PacBio_MtSinai).  
Warning-  i had to hack the headers a bit to even get this VCF to run & even so I had a filter parsing error that I avoided by only processing passing filter calls.  But when just processingfilter PASS calls, I hit a parsing error that appears to be easily fixable.

In this VCF file, SVLEN can sometimes be '=.', which chokes truvari.py at line 264.  I hacked in a fix that handles the SVLEN=. as follows:

>     if "SVLEN" in entry.info:
>         if type(entry.info["SVLEN"]) in [list, tuple]:
>             if entry.info['SVLEN'][0] is None:
>                 size = entry.stop - entry.start
>             else:
>                 size = abs(entry.info["SVLEN"][0])
>         else:
>             size = abs(entry.info["SVLEN"])

**Comment by ACEnglish** [comment]
This is an interesting one. You've made a very reasonable fix that I'm considering adopting. However, there's two considerations.

First, if I were to actually incorporate this change, there would need to be more edge cases to check. For example, your proposed sub-if would only catch those VCFs in which the INFO Header for SVLEN defined `Number=.`. An equally valid definition is `Number=1`, such that the `entry.info["SVLEN"]` would not be `in [list, tuple]`, so the last line `size = abs(entry.info["SVLEN"])` would do the choking. 

Second, I don't know for certain that `SVLEN=.` is a valid tag and perhaps Truvari really should be choking on these entries. The VCF Format specification doesn't explicitly disallow a null SVLEN, but it does have a clear definition of what the value should be. A flaw in the format is that there are a lot of 'should' specifications, but very few enforced 'musts'. 
I've often found that VCFs reported by some tools take liberties with the format's flexibility. Instead of trying to account for every edge case, Truvari expects a stricter adherence to the specification. I would suggest a VCF cleaning/qc step before using Truvari. For example, the SVLEN tag could be stripped with `bcftools annotate -x INFO/SVLEN`, or a custom script could set it to the correct value.
