### ISSUE TITLE
truvari doesn't compute the predicted haplotype sequence of the sample genome in the case of DELs 

### ISSUE THREAD

**Issue by petermchale** [spiralgenetics/truvari#49]
@ACEnglish:  

I've produced some test cases to illustrate what I mean at: 
https://github.com/petermchale/truvari/blob/develop/tests/sample-haplotype-test/README.md
That link also describes what I think is the solution. 
Let me know if you agree. 

Best, 
Peter McHale

**Comment by ACEnglish** [comment]
Hi Peter,

Thank you for this detailed ticket. I've been looking over it for a little while now. Everything seems valid from your report. However, I haven't yet  incorporated your suggested edit. My concern is centered around the idea that when Truvari doesn't consider the deleted sequence during sequence similarity computation, nearly identical deletions will be unfairly penalized. 

For example, here's a real GIAB deletion (base) and a corresponding BioGraph SV call.

```
vcf start stop deleted_seq
base 83149849 83149908 TCCACAGATTTAAGAGAATACGAGAGAGCATGAAGGAATGAGAAAAATAAATGAATGCC
comp 83149850 83149910 CCACAGATTTAAGAGAATACGAGAGAGCATGAAGGAATGAGAAAAATAAATGAATGCCAA
```

These two calls have a 96% reciprocal overlap, and only a base or two difference in position.
The existing code creates the haplotypes and pctsim of:
```
g CTCCACAGATTTAAGAGAATACGAGAGAGCATGAAGGAATGAGAAAAATAAATGAATGCCAA 
b TTCCACAGATTTAAGAGAATACGAGAGAGCATGAAGGAATGAGAAAAATAAATGAATGCCAA
pctsim = 0.9838709677419355
```
However, your proposed changes create
```
g TAA
b TGT
pctsim = 0.3333333333333333
```

I'm still drafting ideas for how both your cases and my cases could be correctly identified. My leading idea at the moment is changing the haplotypes created for deletions by adding a larger buffer around the breakpoints. The difficulty is identifying how much of a buffer should be included. It's likely that there will need to be a dynamic buffer amount for both.

Let me know if you have any thoughts. I'll be working on this and will get back to you with a solution if I find one.

Have a great day,
~/Adam English

**Comment by petermchale** [comment]
Thanks for reviewing this. 

To be honest, I don't understand why the current code does not produce exactly identical sequences for base and comp in the example above (and more generally for all cases) since, as I understand it, the code is constructing those sequences entirely from the reference, either by pulling from the reference directly, or by pulling the REF allele. 

Yes, the percent sequence similarity goes down, as I found too (https://github.com/petermchale/truvari/blob/develop/tests/sample-haplotype-test/classifications_sequence_similarities.tsv), but that was exactly my point: with the current code every base and comp will look similar, even when the predicted sample haplotypes are quite different. 

All the matches that the old code generates can be recovered with the new code by reducing the sequence similarity threshold. In my experiments, I had to reduce it to 0.01, to capture matches of the type you describe above. But now you have the opposite problem to the problem with the original code: every base and comp looks different so you have to compensate by reducing the threshold! 

The other approach, which you describe, is to incorporate a dynamic flanking sequence, which will obviously increase similarity in the new version of the code, allowing you to increase the sequence-similarity threshold for matching. But now you can make any two calls sufficiently similar to one another by just extending the flanking sequence so much that it contains reference sequence common to both calls. 

I think the real answer to this problem is empirical: take a collection of base and comp calls where you know a priori which ones should be matched and which ones shouldn't and then repeatedly alter the flanking size and similarity threshold until truvari produces matches as close as possible to the set of true matches. In other words, use "labeled" data (the "true" matches and mismatches) to "learn" the optimal values of `flank_seq_size` and `seq_sim_threshold` by randomly altering them iteratively in an effort to reduce a "loss function" (how different predicted and true matches are). 

All this is just a long-winded way of suggesting that you use supervised learning to solve the problem.  

Hope that makes sense.

**Comment by ACEnglish** [comment]
1) Yes - there was a problem I noticed last night of why the pctsim wasn't 100% for some my example above. Turns out I had some off-by-one errors that have been fixed by switching from `pyfaidx.Fasta` to `pysam.FastaFile`.

2) Here's another interesting observation... In your test data, the incorrectly matched calls (chr13) have another unique characteristic compared to the others:

```python
import truvari
import pysam

for a, b in zip(pysam.VariantFile("base.vcf"), pysam.VariantFile("comp.vcf")):
    print(a.chrom, truvari.entry_reciprocal_overlap(a, b))
# chr1 0.5346534653465347
# chr3 0.5971223021582733
# chr10 0.9245283018867925
# chr11 0.9428571428571428
# chr13 0
```
By default, `--pctovl` is set to 0. I have kept this parameter off because most VCFs I work with have point resolved insertions, that don't contain a physical span over the reference, and therefore cannot have a reciprocal overlap.

I have changed this behavior so that now `--pctovl` is only applied to `truvari.entry_variant_type(entry) == "DEL"`. The parameter default will remain at 0 for now.

3) Additionally, I have run some tests and shown that over internal data, adding a buffer of `(haplotype_end - haplotype_start) * buffer` to the start and end coordinates of the region over which we create the haplotype seems to generally have a positive effect reducing the number of 'suspect' high sequence similarity matches. This is exposed in a `--buffer` parameter (default 0.1). The behavior of the parameter on your test cases is shown below.

```python
import Levenshtein
import truvari
import pysam

rfn = "/reference/grch38_noalt_decoy/source.fasta"
ref = pysam.FastaFile(rfn)
print("chrom rec_ovl new_sim")
for a, b in zip(pysam.VariantFile("base.vcf"), pysam.VariantFile("comp.vcf")):
    ostr = ""
    for i in range(0, 30, 10):
        new_sim = truvari.entry_pctsim_lev(a, b, ref, buf_len = i / 100)
        ostr += "\t%.2f" % (new_sim)
    print('%s\t%.2f%s' % (a.chrom, truvari.entry_reciprocal_overlap(a, b), ostr))

# Checking my exmaple
rfn = "/reference/hs37d5/source.fasta"
ref = pysam.FastaFile(rfn)
v = pysam.VariantFile("missing.vcf")
a = next(v)
b = next(v)
ostr = ""
for i in range(0, 30, 10):
    new_sim = truvari.entry_pctsim_lev(a, b, ref, buf_len = i / 100)
    ostr += "\t%.2f" % (new_sim)
print('%s\t%.2f%s' % ('mine', truvari.entry_reciprocal_overlap(a, b), ostr))
```

Results of pctsim for multiple values of `--buffer`
```
chrom rec_ovl	buf=.0	buf=.1	buf=.2
chr1	0.53	0.74	0.85	0.89
chr3	0.60	0.59	0.77	0.84
chr10	0.92	0.88	0.97	0.98
chr11	0.94	1.00	1.00	1.00
chr13	0.00	0.64	0.73	0.78
mine	0.97	0.40	0.90	0.94
```

I don't think this is the absolute best answer. Your proposal sounds interesting and I'll give it more though. There's also a possibility that a design I've been working on in the background to replicate the 'graph' type comparison performed by `rtg vcfeval` could address this problem as well as other phasing/complex-representation issues that are of particular interest to me.

Let me know your thoughts on these changes.
