### ISSUE TITLE
No 2.0 Tag

### ISSUE THREAD

**Issue by WEClarke** [spiralgenetics/truvari#51]
In the updates section you mention Truvari 2.0 but there is no tag for the release.

**Comment by ACEnglish** [comment]
I'm still working on version 2. The discrepancy between the WIKI and the tags/pypi releases is a side effect of me not having version controlled documentation. I've updated the repository's settings so that the default branch is `master`, which is more in line with my [git-flow](https://nvie.com/posts/a-successful-git-branching-model/) model, and better represents the repository as user-facing more than developer-facing.

**Comment by WEClarke** [comment]
Thanks for the update Adam, looks like you've put a lot of effort into this since I last looked at it and am looking forward to getting into the new features.

**Comment by ACEnglish** [comment]
Please feel free to test out the develop branch If anything catches your eye. I'm happy to address any questions/bugs/feature requests as I build.
