### ISSUE TITLE
truvari does not support variants in BND notation.

### ISSUE THREAD

**Issue by d-cameron** [spiralgenetics/truvari#55]
VCF allows any structural variant to be reported in `BND` notation. There is no difference between a breakpoint-based caller report a variant as a `<DEL>` and the caller reporting the same breakpoint in `BND` notation. Both calls are equivalent.

This means truvari does not support benchmarking of caller such as GRIDSS and Hydra.

**Comment by d-cameron** [comment]
For example, The following deletion
```
1234567890
ATAGGTTCGC
AT-----CGC
```
Can be represented as any of:
```
#CHROM    POS    ID    REF    ALT    QUAL    FILTER    INFO
contig    2    del_indel    TAGGTT    T    .    .    
contig    3    del_svtype    A    <DEL>    .    .    SVTYPE=DEL;SVLEN=-5;END=7
contig    2    del_bnd_1    T    T[contig:8[    .    .    SVTYPE=BND;MATEID=del_bnd_2;EVENT=example_del;EVENTTYPE=DEL
contig    8    del_bnd_2    C    ]contig:2]C    .    .    SVTYPE=BND;MATEID=del_bnd_1;EVENT=example_del;EVENTTYPE=DEL

```

**Comment by ACEnglish** [comment]
Correct. The first two representations would be handled, but not the BND.  Because BNDs can have multiple representations/orientations in order to capture complex rearrangements, which have many considerations when performing matching/counting, Truvari assumes simple deletions and insertions. I would advise you create a parser that will translate the BND into one of the other representations.
