### ISSUE TITLE
template not working properly

### ISSUE THREAD

**Issue by scalavision** [spiralgenetics/truvari#59]
I get this output in my template sheet:

```
True Positives | 2,795
False Negatives | 1,404
False Positives | 77
Precision | None
Recall | /gold/HG002_DEL_Tier1_v0.6.vcf.gz
F1 | 97.32%
```

The wrong cells are Precision and Recall. I am using truvari version 2.0.2, and using the path to the template given at the wiki:

https://docs.google.com/spreadsheets/d/1T3EdpyLO1Kq-bJ8SDatqJ5nP_wwFKCrH0qhxorvTVd4/edit?usp=sharing

It seems Precision should use $RawData.B181 and Recall $RawData.B182

**Comment by ACEnglish** [comment]
I'm unable to recreate this issue. Could you double check that your copy/paste of the `giab_report.txt` was successful? If so, could you attach the `giab_report.txt` so that I can examine it?

Attached is a random report file I used that didn't have this issue. You could also compare your giab_report against this one.
[giab_report.txt](https://github.com/spiralgenetics/truvari/files/5563064/giab_report.txt)

**Comment by scalavision** [comment]
Thanks @ACEnglish , seems I must have accidentally used an old template in my script. Sorry for the inconvenience, and thank you for the excellent tool!

**Comment by eldariont** [comment]
Hi Adam,

I'm experiencing a similar issue with the current version of Truvari (2.0.2) installed via pip. 

As described in the [wiki](https://github.com/spiralgenetics/truvari/wiki/bench#using-the-giab-report), I made a copy of the [Truvari Report Template](https://docs.google.com/spreadsheets/d/1T3EdpyLO1Kq-bJ8SDatqJ5nP_wwFKCrH0qhxorvTVd4/edit#gid=0). Then, I pasted the content of my [giab_report.txt](https://github.com/spiralgenetics/truvari/files/5776852/giab_report.txt) into Cell A3 of the `Raw Data` tab. While most of the values in the `Formatted` tab look fine there are several problems:
- The first section about the number of filtered calls does not make any sense because it retrieves the values from `RawData!B173` through `RawData!B178` which for my file points to different values: `TP-base_TP-gt, TP-call, TP-call_FP-gt, TP-call_TP-gt, base cnt, call cnt`.
- In the second section, the Precision and Recall retrieve their values from `RawData!B180` and `RawData!B181` which for my file points to `gt_f1, gt_precision`.
- Similarly, the section "Genotypes" retrieves the values from `RawData!B205` and the following which for my file points into the middle of the `Args` section of the `giab_report.txt`

I compared my `giab_report.txt` to the one you provide above and both files are similar. When I paste the content of your file into the template it yields the same result.

Do you have any idea what might be the problem? Which template have you been testing with?

Best
David
