### ISSUE TITLE
cannot install using conda

### ISSUE THREAD

**Issue by yekaizhou** [spiralgenetics/truvari#65]
I tried using `conda install -c bioconda truvari`

And it first jumped out 
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.

Then it told me
> Found conflicts! Looking for incompatible packages.
> Specifications:
>   truvari -> python[version='<3|>=2.7,<2.8.0a0']
> Your python: python=3.8

I am wondering what should I do then

**Comment by ACEnglish** [comment]
I'm unfamiliar with conda, but it looks like it's trying to install an older version of truvari that required python 2 into your python3 environment. Truvari was [updated](https://github.com/spiralgenetics/truvari/wiki/Updates) some time ago to run on python 3. 

I actually don't maintain the conda package and I'm unsure of how it got there. The package management I maintain is via [PyPi](https://pypi.org/project/Truvari/) so that the command `pip install truvari` is available. I can look into where that came from and maybe upload to anaconda. In the meantime, I'd recommend reading [this](https://www.anaconda.com/blog/using-pip-in-a-conda-environment) and trying to use the documented installation procedure.

**Comment by yekaizhou** [comment]
Thanks a lot. Please let me know when you have updated the Python3 version to anaconda.
