### ISSUE TITLE
Relatively low performance on different SV size

### ISSUE THREAD

**Issue by SQLiu-youyou** [spiralgenetics/truvari#67]
The overall F1 of the caller using the command [truvari bench -b base.vcf -c comp.vcf -o "file" -p 0 --sizemax 100000000] is  0.706169.
However when I tried to change the size range via -s and [--sizemax], the F1 score were relatively low:
50-99:0.62504, 100-499:0.70556, 500-1k:0.643505, 1k_5k:0.662128, 5k-10k:0.590786, over10k: 0.68917
The results really make me feel puzzled. Is there something I forget or use 
inappropriately？

**Comment by ACEnglish** [comment]
Hi,

Since the F1 score is the harmonic mean of the precision and recall, it's hard for me to say for certain how the subsets' F1 should relate to the overall F1. 
Therefore, I suggest you look at the full reported summary information and see if it still makes sense. For example, do the number of calls compared overall equal the sum of the number of calls compared per-subset? 

Have a great day,
~/Adam English
