### ISSUE TITLE
Unable to parse comparison vcf file

### ISSUE THREAD

**Issue by wjj666** [spiralgenetics/truvari#70]
Hi, I want to compare my vcf file (generated with **whatshap**) with **[GIAB SV v.0.6 (SVs >= 50bp, GRCh37)](https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/)** by **Truvari.** But when I run this command:

> truvari bench -c phased_hic.vcf.gz -b HG002_SVs_Tier1_v0.6.vcf.gz -f ref.fa -o ./out 

it leads to this error:

> 2021-06-15 01:07:17,577 [INFO] Running /***/truvari bench -c phased_hic.vcf.gz -b HG002_SVs_Tier1_v0.6.vcf.gz -f ref.fa -o ./out
> 2021-06-15 01:07:17,577 [INFO] Params:
> {
>     "base": "HG002_SVs_Tier1_v0.6.vcf.gz",
>     "comp": "phased_hic.vcf.gz",
>     "output": "./out",
>     "reference": "ref.fa",
>     "giabreport": false,
>     "debug": false,
>     "prog": false,
>     "refdist": 500,
>     "pctsim": 0.7,
>     "buffer": 0.1,
>     "pctsize": 0.7,
>     "pctovl": 0.0,
>     "typeignore": false,
>     "gtcomp": false,
>     "bSample": null,
>     "cSample": null,
>     "sizemin": 50,
>     "sizefilt": 30,
>     "sizemax": 50000,
>     "passonly": false,
>     "no_ref": false,
>     "includebed": null,
>     "multimatch": false
> }
> 2021-06-15 01:07:17,674 [INFO] Creating call interval tree for overlap search
> 2021-06-15 01:07:17,676 [ERROR] Unable to parse comparison vcf file. Please check header definitions
> 2021-06-15 01:07:17,676 [ERROR] Specific error: "invalid contig `7`"

Is there something wrong with the vcf file? Could you please help me solve this problem? And could you please talk more about the how to prepare **reference.fasta**? Does the reference.fasta indicates the one which I used for generate vcf file with **whatshap**?

Thank you very much.

**Comment by ACEnglish** [comment]
Hello,

We've documented common challenges with using VCFs on the [wiki](https://github.com/spiralgenetics/truvari/wiki) with [a link to a tool](https://github.com/acenglish/usable_vcf) that can help you validate your files. 
To answer your question directly, it seems you probably want to check your header lines for their definitions of each `##contig`. The reference should be the reference over which your base and comparison calls were made. Since you're using GIAB v0.6, that reference should be hg19.

Have a great day,
~/Adam
