### ISSUE TITLE
explainantion on --gtcomp  and genotype concordance

### ISSUE THREAD

**Issue by prasundutta87** [spiralgenetics/truvari#98]
Hi,

I am using the latest version of Truvari (v3.1.0) and had a query on truvari bench program.

When running without --gtcomp (what most benchmarking procedures do), in the giab report, I get the different value of in "gt_concordance". This value is different from "gt_concordance" in the summary.txt output. Why is it the case? Also, when --gtcomp is false, why is gt_concordance still calculated?

When --gtcomp is TRUE, how is the benchmarking done? All the precision, recall and F1 scores were different from the above case.

Regards,
Prasun

**Comment by ACEnglish** [comment]
Hello,

The `gt_concordance` difference in `giab_report.txt` and `summary.txt` was fixed last week in 2d035ff. Until I make a new release, you can work off of`v3.2.0-dev` by cloning the repository and installing. The difference was being caused by a formatting error where `f1` was being placed in the `giab_report.txt`'s `gt_concordance` field.

For Truvari, genotype comparison with `--gtcomp` means calls must have an identical genotype to match. I left this as a parameter because checking for the presence of an allele (e.g. is this deletion in `--base` and `--comp` VCFs) is different than checking for the presence AND the correct genotyping of an allele (e.g. is this deletion in both VCFs and HET). By leaving it as a parameter, users have control over which check they'll perform. 

However, we still report the `gt_concordance` when `--gtcomp==False` mainly because it's easy to calculate, but I also feel its useful and informative. This number is "How many matching calls have the same genotype?"

As for why you're seeing different numbers with `--gtcomp`, that's because the parameter specifies that two variants must have the same genotype  to be considered a true-positive. Note that when using `--gtcomp`, the genotype concordance will be 100% because concordance is calculated only on matching calls (TPs). So by requiring matching genotypes, assuming you have an imperfect genotyper, performance metrics will be lower.

Let me know if that answers your question or if you'd like to know more.
Have a great day,
~/Adam

**Comment by prasundutta87** [comment]
Thanks a lot for the quick explaination. I just realised that f1 and gt_concordance values are the same in the giab_report.txt. As of now, I will only concentrate on the summary.txt file for gt_concordance. 

So, according to your explaination of your last paragraph, if I am benchmarking the genotyper of tool, I should aim for higher performance metrics with --gtcomp?

**Comment by ACEnglish** [comment]
For the HG002 Tier1 bed: No, you don't need to subset the VCF. The `--includebed` option will do that for you. Also, It's generally recommended to use `--passonly` because the GIAB VCF has multiple FILTERs applied. 

For the "higher performance metrics with --gtcomp": If you're interested in genotyper performance, you can go either way to get to the same answer. The 'better' method will depend on which metrics you want to collect and how you'll report them.

If you use `--gtcomp`, your tp-base/tp-call counts will be what you're trying to optimize. 
If you don't use `--gtcomp`, you'll have the Maximum number of variants you could possibly genotype correctly reported in the tp-base/tp-call counts. Then the `gt_concordance` will report the percent of those tp-base/tp-call variants correctly genotyped, and you'll want to maximize that. So tp-base/tp-call will be the same run to run.

This might be off-topic, but if you choose to not use `--gtcomp`,  I think you may find Discussion #87 informative. After using `truvari vcf2df -b -i -f`, you can create a pandas DataFrame of your bench results. That DataFrame can help you script up more detailed analysis of your results. In the discussion, I show an example plot a ROC of your calls' performance with respect to QUAL, which you could change to something like GQ. For example:

```python
# Plotting the total curve
fpr, tpr, threshold = metrics.roc_curve(all_data["state"] == 'tp', all_data["HG002_GQ"])
auc = metrics.roc_auc_score(all_data["state"] == 'tp', all_data["qual"])
plt.plot(fpr, tpr, label="TOT auc=%.2f" % (auc))
```
Where `HG002_GQ` is whatever column holds the genotyping quality scores of your data. You can imagine lots of different subsets and views of the data that might help you dig into your results deeper after you perform a single `truvari bench`. For example, you could analyze the GQ of variants with matching genotype separately from those without matching genotype by leveraging the `truvari bench` annotation `GTMatch` (See (wiki)[https://github.com/spiralgenetics/truvari/wiki/bench#definition-of-annotations-added-to-tp-vcfs] for all annotations).

Maybe something like:
```python
import joblib
data = joblib.load("your_dataframe.jl")
match_correct_gt = data[(data["state"] == 'tp') & (data["GTMatch"])]
match_incorrect_gt = data[(data["state"] == 'tp') & (~data["GTMatch"])]
print(match_correct_gt["HG002_GQ"].describe())
print(match_incorrect_gt["HG002_GQ"].describe())
```
Note I didn't test this code. Just jotted down something similar to what you'd want to make.

**Comment by prasundutta87** [comment]
Thank you so much, Adam! This has been extremely helpful. I will explore the options. I will be actually working with trio data, so I need the genotype to be as correct as possible. I will hopefully try a joint genotyper as well for the trios such as LRcaller. 

Just a last query. How does truvari deal with multisample VCF file. I used SURVIVOR merge to make a consensus set. Does truvari only take the first sample for its analysis (both gtcomp and performace metrics)?

**Comment by prasundutta87** [comment]
That's great, Adam! Thanks a lot for your help. Some tools do report a reference-homozygous genotypes for SVs. Not sure why they do that. Is there any reason behind that? I would assume that there may be no variation at that site.

**Comment by ACEnglish** [comment]
It probably varies from tool to tool, so I can't speak on that definitively. But if I were to guess, reference homozygous from a discovery tool is a little unusual. Probably the discovery is decoupled from the genotyping. There might be 1 or 2 reads that suggest an alternate allele, but the coverage is 2x alt / 30x ref so it reports `0/0`. It's common to get reference homozygous from genotyping tools, though; especially when you're genotyping for variants that may not be present in the sample just like your assumption.

**Comment by prasundutta87** [comment]
Makes sense. Thanks a lot for clearing my queries, Adam! :-)
